
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE

management:
  shell:
    auth:
      simple:
        user:
          name: user
          password: pass

  my:
    refreshable:
      message: Hi there! 1

server:
  port: 8091
